fix: Typo fixed in license notice in every file
florgon/cc-api pull request #38
Opened 2023-10-07 13:01 UTC by Rhythm-08

2023-10-08 14:36 UTC, stepanzubkov requested changes

2023-10-08 14:36 UTC, stepanzubkov commented on COPYING
You should not touch COPYING file; only license notices

2023-10-09 14:31 UTC, Rhythm-08 commented on COPYING
Fixing

2023-10-11 17:06 UTC, stepanzubkov approved these changes

2023-10-12 12:56 UTC, merged